#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
branch="$(git rev-parse --abbrev-ref HEAD)"

# With this code you can select which branch the users can't make any commit. #

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

npm run lint
npm run test
