name: Test Code
on:
  pull_request:
  push:
    branches:
      - develop/*
jobs:
  test-code:
    environment:
      name: QA_AUTH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Build
      - name: Set Homepage
        run: npm run setHomepage
        run: CI=false npm run build 
      - name: Deploy QA
        run: netlify deploy --prod --auth ${{ secrets.QA_AUTH }} --site ${{ secrets.SITE }}
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test

      
